version: "3"

services:
  webserver:
    image: puckel/docker-airflow:1.10.9
    ports:
      - "8080:8080"
    volumes:
      - ./dags:/usr/local/airflow/dags
      - ./database:/usr/local/airflow/airflow.db
    environment:
      - LOAD_EX=n
      - EXECUTOR=Local
